# GitHub Pages Jekyll Configuration
title: "Minecraft Bedrock Enterprise Laws"
description: "Professional development standards for AI-assisted Minecraft Bedrock scripting with private repository validation"
baseurl: "/minecraft-bedrock-laws"
url: "https://013sc3n3.github.io"

# Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# SEO and metadata
lang: en-US
author: "013SC3N3"
keywords: "minecraft, bedrock, scripting, laws, ai, chatgpt, claude, enterprise, development, mojang, repository, validation"

# GitHub repository
repository: "013sc3n3/minecraft-bedrock-laws"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections for better organization
collections:
  laws:
    output: true
    permalink: /laws/:name/
  patterns:
    output: true
    permalink: /patterns/:name/
  examples:
    output: true
    permalink: /examples/:name/

# Navigation structure
navbar_links:
  "Quick Start":
    - title: "ChatGPT Version"
      url: "/quick-start/chatgpt"
    - title: "Claude Version"  
      url: "/quick-start/claude"
    - title: "API Blacklist"
      url: "/api/blacklist"
  "Laws":
    - title: "Core Principles"
      url: "/laws/core-principles" 
    - title: "Architecture"
      url: "/laws/architecture"
    - title: "Development"
      url: "/laws/development"
    - title: "Scaling"
      url: "/laws/scaling"
  "Resources":
    - title: "Code Patterns"
      url: "/patterns/"
    - title: "Examples"
      url: "/examples/"
    - title: "API Reference"
      url: "/api/"
    - title: "Validation"
      url: "/validation/"

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# Include files
include:
  - _pages

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "laws"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "patterns"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "examples"
    values:
      layout: "default"

# Custom variables for the site
minecraft:
  version: "1.21.82"
  server_api_version: "1.19.0"
  ui_api_version: "1.3.0"
  
repository_info:
  private_bedrock_samples: "013sc3n3/bedrock-samples"
  private_scripting_libraries: "013sc3n3/minecraft-scripting-libraries"
  private_debugger: "013sc3n3/minecraft-debugger"
  private_creator_tools: "013sc3n3/minecraft-creator-tools"
  last_sync: "2025-05-22"
  
ai_optimization:
  chatgpt_max_size: "2KB"
  claude_max_size: "18KB"
  context_chunks: 4
